baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'tale'

[menu]
  [[menu.main]]
    identifier = "main"
    name = "Main"
    title = "Main"
    url = "/main"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
