baseURL = 'https://rubenmanero.github.io/prueba/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'tale'

[Author]
  name="Rubén Manero"

[menu]
  [[menu.main]]
    identifier = "main"
    name = "Main"
    title = "Main"
    url = "/main"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[params]
  css = ["css/estilos.css"]